# Modified by zhiyb (Yubo Zhi)

TRG	= DAC
SRC	= main.c dac.c

PRGER		= usbasp
MCU_TARGET	= atmega644p
MCU_FREQ	= 12000000

EFUSE	= 0xFF
HFUSE	= 0x9C
LFUSE	= 0xE7

LOG	= ~/.make_avr.log

SRCDIR	?= .
include $(SRCDIR)/../Makefile_AVR.defs
