LIBNAME		= liblist
LIBSRC		= portraitlist.cpp
# landscapelist.cpp

LIB		= tft-cpp rTouch

MCU_TARGET	?= atmega644p
MCU_FREQ	?= 12000000 

OPTIMIZE	?= -Os
DEFS		?= -DF_CPU=$(MCU_FREQ)

include ../Makefile.in
