# Author: Yubo Zhi (normanzyb@gmail.com)

TRG	= WS2812B
SRC	= main.c
SUBDIRS	= common rgbled

PRGER		= usbasp
MCU_TARGET	= atmega644p
MCU_FREQ	= 12000000

SRCDIR	?= .
include $(SRCDIR)/../Makefile_AVR.defs
