# Modified by zhiyb (Yubo Zhi)

TRG	= 4x4x4
SRC	= effect.cpp led.cpp main.cpp
VERSION	= 0.0.1

PRGER		= usbasp
MCU_TARGET	= atmega644p
MCU_FREQ	= 12000000
OPTLEVEL	= s

EFUSE	= 0xFF
HFUSE	= 0x9C
LFUSE	= 0xE7

LOG	= ~/.make_avr.log

include ../Makefile.defs
