# Author: Yubo Zhi (normanzyb@gmail.com)

TRG	= RGBLEDMatrix
SRC	= main.cpp
SUBDIRS	= common

PRGER		= usbasp
MCU_TARGET	= atmega644p
MCU_FREQ	= 12000000
OPTLEVEL	= s

LIBS	+= -lm

SRCDIR	?= .
include $(SRCDIR)/../Makefile_AVR.defs
