# Modified by zhiyb (Yubo Zhi)

TRG	= Pong
SRC	= game.c main.c rotary.c sound.c
LIB	= tft common
LIBDIR	= ../lib

PRGER		= usbasp
MCU_TARGET	= atmega644p
MCU_FREQ	= 12000000
OPTLEVEL	= s

EFUSE	= 0xFF
HFUSE	= 0x9C
LFUSE	= 0xE7

include ../Makefile.defs
